pipeline {
    agent {
        docker {
            image 'node:14'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
        HOME = '.'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'pwd'
                sh 'dir'
                sh 'pwd'
            }
        }
        stage('Test') {
            steps {
                sh './my-app/jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './my-app//jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './my-app//jenkins/scripts/kill.sh'
            }
        }
    }
}